# Generated by Django 5.0.6 on 2024-05-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maddalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanun', models.CharField(max_length=250)),
                ('maddalar', models.TextField()),
                ('number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'madda',
                'verbose_name_plural': 'maddalar',
                'db_table': 'maddalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KanunUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='books/')),
            ],
            options={
                'verbose_name': 'KanunUpload',
                'verbose_name_plural': 'KanunUploads',
                'db_table': 'KanunUpload',
                'ordering': ['id'],
                'unique_together': {('name', 'file')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
