# Generated by Django 5.0.6 on 2024-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soragjogap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maddalar',
            name='number',
        ),
    ]
